sidebar:
  entries:
    - title: Project Astra docs
      url: /index.html
    - section: get-started
    - section: use
    - section: learn
    - section: solutions
    - section: apis
    - section: training
    - section: support

homepage:
  tiles:
    - title: Get Started
      image: ./media/outline_directions_run_black_18dp.png
      links:
        - title: Learn about Project Astra
          summary: Understand how Project Astra works.
          url: /someurl.html
        - title: Quick start
          summary: Get started quickly with Project Astra.
          url: /someurl.html
        - title: FAQ
          summary: Read frequently asked questions about Project Astra.
          url: /someurl.html
    - title: Use Project Astra
      links:
        - title: Register applications
          summary: Enable Project Astra to manage and protect your apps.
          url: /someurl.html
        - title: Back up your apps
          summary: Create recovery points for your apps in case of failure.
          url: /someurl.html
        - title: Migrate an app
          summary: Migrate an app to another cluster.
          url: /someurl.html
    - title: Demos & tutorials
      links:
        - title: Deploy MariaDB (video)
          summary: Deploy MariaDB from a Helm chart and register it with Project Astra.
        - title: Deploy MySQL (video)
          summary: Deploy MySQL from a Helm chart and register it with Project Astra.
        - title: Deploy Postgres
          summary: Deploy Postgres from a Helm chart and register it with Project Astra.
    - title: Blogs & community
      links:
        - title: The Promise of Stateful Applications in the Cloud
          summary: How Rroject Astra provides robust storage, easy-to-consume data services, and application and data portability.
        - title: Project Astra Community
          summary: Connect with peers, ask questions, exchange ideas, and share best practices.
