sidebar:
  entries:
    - title: Astra docs
      url: /index.html
    - section: release-notes
    - section: get-started
    - section: use
    - section: automation
    - title: Automate with REST
      url: /automation.html
    - section: learn
    - section: solutions
    - section: support
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      #image: ./media/outline_directions_run_black_18dp.png
      links:
        - title: Learn about Astra
          summary: Understand how Astra works.
          url: /get-started/intro.html
        - title: What's new
          summary: Learn what's new with Astra.
          url: /release-notes/whats-new.html
        - title: Quick start
          summary: Get started quickly with Astra.
          url: /get-started/quick-start.html
        - title: FAQ
          summary: Read frequently asked questions.
          url: /get-started/faq.html
    - title: Use Astra
      links:
        - title: Manage applications
          summary: Start managing your apps from Astra.
          url: /use/manage-apps.html
        - title: Protect your apps
          summary: Create recovery points for your apps in case of failure.
          url: /use/protect-apps.html
        - title: Migrate an app
          summary: Migrate an app to another cluster.
          url: /use/clone-apps.html
        - title: Set up billing
          summary: Set up billing for the Premium Plan.
          url: /use/set-up-billing.html
    - title: Demos & tutorials
      links:
        - title: Astra videos
          summary: Watch videos that show how to use Astra.
          url: /get-started/videos.html
        - title: Deploy MariaDB
          summary: Deploy MariaDB from a Helm chart and register it with Astra.
          url: /solutions/mariadb-deploy-from-helm-chart.html
        - title: Deploy MySQL
          summary: Deploy MySQL from a Helm chart and register it with Astra.
          url: /solutions/mysql-deploy-from-helm-chart.html
    - title: Solution briefs
      links:
        - title: Astra with DataStax Enterprise and Apache Cassandra
          summary: Full lifecycle management in a cloud-native Kubernetes environment.
          url: https://cloud.netapp.com/hubfs/SB-4134-0321-DataStax-Cassandra-Guide%20(1).pdf
        - title: PostgreSQL DBaaS with Astra
          summary: Use Astra to simplify day 2 operations of DBaaS for PostgreSQL.
          url: https://cloud.netapp.com/hubfs/SB-4122-0221-PostgresSQL-DBaaS-with-Astra%20(2).pdf
        - title: MySQL DBaaS with Astra
          summary: Use Astra to simplify day 2 operations of DBaaS for MySQL.
          url: https://cloud.netapp.com/hubfs/SB-4110-0221-MySQL-Astra%20(2).pdf
        - title: Simplify Jenkins app and data lifecycle management
          summary: Deliver data protection and portability to Jenkins on GKE.
          url: https://cloud.netapp.com/hubfs/SB-4100-Jenkins%20(2).pdf
    - title: Blogs & community
      links:
        - title: Slack
          summary: Ask questions, exchange ideas, and share best practices.
          url: https://netapppub.slack.com/#astra
        - title: The first application-aware data management service for Kubernetes
          summary: How Astra manages, protects, and moves Kubernetes data-rich containerized workloads.
          url: https://cloud.netapp.com/blog/blg-astra-data-management-services-for-kubernetes-applications
        - title: Kubernetes Hub
          summary: A curated collection of blog postings to learn more about Kubernetes and persistent storage.
          url: https://cloud.netapp.com/kubernetes-hub
